import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";
import { sleep } from "../../utils";

export default function Home({ random }) {
  const { locale } = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Dynamic page!</h1>
        <h3 className={styles.title}>SSR: {random}</h3>

        <Link className={styles.description} locale={locale} href="/">
          Click here to go home!
        </Link>
      </main>
    </div>
  );
}

export const getServerSideProps = async ({ query: { slug } }) => {
  await sleep(250);

  // fake 404 check
  if (slug.includes('404')) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      random: Date.now(),
    },
  };
};
